// <auto-generated />
namespace Entity_Framework6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialForce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialForce));
        
        string IMigrationMetadata.Id
        {
            get { return "202210011849066_Initial-Force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
